CREATE TABLE "mcq_questions" (
	"id" text PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"reviewer_id" text,
	"reviewed_at" timestamp with time zone,
	"difficulty" text NOT NULL,
	"is_demo_mode" boolean DEFAULT false NOT NULL,
	"company_type" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"prompt" text NOT NULL,
	"topic" text NOT NULL,
	"subtopics" text[] DEFAULT '{}' NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"estimated_time_minutes" integer DEFAULT 0 NOT NULL,
	"ai_evaluation_hint" text,
	"companies" jsonb,
	"positions" text[] DEFAULT '{}' NOT NULL,
	"primary_tech_stack" text[] DEFAULT '{}' NOT NULL,
	"interview_types" text[] DEFAULT '{}' NOT NULL,
	"seniority_levels" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"created_by" text NOT NULL,
	"correct_answer_text" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "open_questions" (
	"id" text PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"reviewer_id" text,
	"reviewed_at" timestamp with time zone,
	"difficulty" text NOT NULL,
	"is_demo_mode" boolean DEFAULT false NOT NULL,
	"company_type" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"prompt" text NOT NULL,
	"topic" text NOT NULL,
	"subtopics" text[] DEFAULT '{}' NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"estimated_time_minutes" integer DEFAULT 0 NOT NULL,
	"ai_evaluation_hint" text,
	"companies" jsonb,
	"positions" text[] DEFAULT '{}' NOT NULL,
	"primary_tech_stack" text[] DEFAULT '{}' NOT NULL,
	"interview_types" text[] DEFAULT '{}' NOT NULL,
	"seniority_levels" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"created_by" text NOT NULL,
	"reference_answers" jsonb
);
--> statement-breakpoint
CREATE TABLE "truefalse_questions" (
	"id" text PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"reviewer_id" text,
	"reviewed_at" timestamp with time zone,
	"difficulty" text NOT NULL,
	"is_demo_mode" boolean DEFAULT false NOT NULL,
	"company_type" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"prompt" text NOT NULL,
	"topic" text NOT NULL,
	"subtopics" text[] DEFAULT '{}' NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"estimated_time_minutes" integer DEFAULT 0 NOT NULL,
	"ai_evaluation_hint" text,
	"companies" jsonb,
	"positions" text[] DEFAULT '{}' NOT NULL,
	"primary_tech_stack" text[] DEFAULT '{}' NOT NULL,
	"interview_types" text[] DEFAULT '{}' NOT NULL,
	"seniority_levels" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"created_by" text NOT NULL,
	"correct_answer" boolean NOT NULL,
	"explanation" text NOT NULL,
	"trickiness_level" integer
);
--> statement-breakpoint
CREATE TABLE "matching_questions" (
	"id" text PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"reviewer_id" text,
	"reviewed_at" timestamp with time zone,
	"difficulty" text NOT NULL,
	"is_demo_mode" boolean DEFAULT false NOT NULL,
	"company_type" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"prompt" text NOT NULL,
	"topic" text NOT NULL,
	"subtopics" text[] DEFAULT '{}' NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"estimated_time_minutes" integer DEFAULT 0 NOT NULL,
	"ai_evaluation_hint" text,
	"companies" jsonb,
	"positions" text[] DEFAULT '{}' NOT NULL,
	"primary_tech_stack" text[] DEFAULT '{}' NOT NULL,
	"interview_types" text[] DEFAULT '{}' NOT NULL,
	"seniority_levels" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"created_by" text NOT NULL,
	"shuffle_left" boolean,
	"shuffle_right" boolean,
	"min_pairs" integer,
	"max_pairs" integer,
	"pairs" jsonb
);
--> statement-breakpoint
CREATE TABLE "system_design_questions" (
	"id" text PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"reviewer_id" text,
	"reviewed_at" timestamp with time zone,
	"difficulty" text NOT NULL,
	"is_demo_mode" boolean DEFAULT false NOT NULL,
	"company_type" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"prompt" text NOT NULL,
	"topic" text NOT NULL,
	"subtopics" text[] DEFAULT '{}' NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"estimated_time_minutes" integer DEFAULT 0 NOT NULL,
	"ai_evaluation_hint" text,
	"companies" jsonb,
	"positions" text[] DEFAULT '{}' NOT NULL,
	"primary_tech_stack" text[] DEFAULT '{}' NOT NULL,
	"interview_types" text[] DEFAULT '{}' NOT NULL,
	"seniority_levels" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"created_by" text NOT NULL,
	"complexity_level" text,
	"non_functional_requirements" text[] DEFAULT '{}' NOT NULL,
	"constraints" text[] DEFAULT '{}' NOT NULL,
	"scaling_focus" text,
	"hints" text[] DEFAULT '{}' NOT NULL,
	"charts" jsonb
);