"use client";

import type { IconType } from "react-icons";
import {
  Gi3dMeeple,
  GiAchievement,
  GiAlarmClock,
  GiDiamondTrophy,
  GiFire,
  GiFlowerTwirl,
  GiHourglass,
  GiImperialCrown,
  GiLaurelCrown,
  GiLightningTrio,
  GiLotus,
  GiMeepleKing,
  GiMetronome,
  GiPodiumWinner,
  GiProgression,
  GiRank3,
  GiRibbonMedal,
  GiSandsOfTime,
  GiSparkles,
  GiSparkSpirit,
  GiStarMedal,
  GiSwordsEmblem,
  GiTargetShot,
  GiTimeTrap,
  GiTrophyCup,
} from "react-icons/gi";

export const ACHIEVEMENT_ICON_MAP: Record<string, IconType> = {
  // Original icon names (for backward compatibility)
  Gi3dMeeple,
  GiProgression,
  GiHourglass,
  GiLaurelCrown,
  GiSandsOfTime,
  GiStarMedal,
  GiMeepleKing,
  GiDiamondTrophy,
  GiTimeTrap,
  GiImperialCrown,
  GiSparkSpirit,
  GiMetronome,
  GiTrophyCup,
  GiSparkles,
  GiLotus,
  GiFlowerTwirl,
  GiPodiumWinner,
  GiRibbonMedal,
  GiSwordsEmblem,
  GiRank3,
  // Friendly name aliases
  Trophy: GiTrophyCup,
  Target: GiTargetShot,
  Star: GiStarMedal,
  Clock: GiAlarmClock,
  Crown: GiImperialCrown,
  Zap: GiLightningTrio,
  Flame: GiFire,
  Sparkles: GiSparkles,
  Medal: GiRibbonMedal,
  Podium: GiPodiumWinner,
  Sword: GiSwordsEmblem,
  Rank: GiRank3,
};

export const ACHIEVEMENT_FALLBACK_ICON = GiAchievement;
